---

## Download plugins

- include_vars: "{{ sonar_plugins_url_file }}"

- name: Download plugins from Bintray
  get_url:
    url="https://sonarsource.bintray.com/Distribution/{{ item.name }}/{{ item.name }}-{{ item.version }}.jar"
    dest="{{ sonar_home }}/extensions/plugins/"
  with_items: "{{ sonar_plugin_definition.sonarsource_bintray | default([]) }}"

- name: Download plugins from Sonarsource Downloads
  get_url:
    url="http://downloads.sonarsource.com/plugins/org/codehaus/sonar-plugins/{{ item.name }}/{{ item.version }}/{{ item.name }}-{{ item.version }}.jar"
    dest="{{ sonar_home }}/extensions/plugins/"
  with_items: "{{ sonar_plugin_definition.downloads_sonarsource | default([]) }}"

- name: Download extra plugins
  get_url:
    url="{{ item }}"
    dest="{{ sonar_home }}/extensions/plugins/"
  with_items:  "{{ sonar_plugin_definition.custom_url | default([]) }}"
